# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OranRUServiceDef.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RfmxNr_pb2 as RfmxNr__pb2
import RfmxPolicy_pb2 as RfmxPolicy__pb2
import RfmxNrResults_pb2 as RfmxNrResults__pb2
import RfsgNr_pb2 as RfsgNr__pb2
import Playback_pb2 as Playback__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16OranRUServiceDef.proto\x12\x10multi_site_instr\x1a\x0cRfmxNr.proto\x1a\x10RfmxPolicy.proto\x1a\x13RfmxNrResults.proto\x1a\x0cRfsgNr.proto\x1a\x0ePlayback.proto\"\t\n\x07Nothing\"\x19\n\x06Status\x12\x0f\n\x07Message\x18\x01 \x01(\t\"-\n\x0bRfmxNrReply\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\r\n\x05\x45rror\x18\x02 \x01(\t\"-\n\x0bRfsgNrReply\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\r\n\x05\x45rror\x18\x02 \x01(\t2\x86\x06\n\x06OranRu\x12\x46\n\x0f\x43onfigureRfmxNr\x12\x14.multi_site_instr.Nr\x1a\x1d.multi_site_instr.RfmxNrReply\x12K\n\x14\x43onfigureAsyncRfmxNr\x12\x14.multi_site_instr.Nr\x1a\x1d.multi_site_instr.RfmxNrReply\x12I\n\x0eInitiateRfmxNr\x12\x18.multi_site_instr.Policy\x1a\x1d.multi_site_instr.RfmxNrReply\x12\x43\n\x0cLaunchRfmxNr\x12\x14.multi_site_instr.Nr\x1a\x1d.multi_site_instr.RfmxNrReply\x12P\n\x14RequestRfmxNrResults\x12\x1b.multi_site_instr.NrResults\x1a\x1b.multi_site_instr.NrResults\x12G\n\x0cInitiateRfsg\x12\x18.multi_site_instr.RfsgNr\x1a\x1d.multi_site_instr.RfsgNrReply\x12I\n\tAbortRfsg\x12\x1d.multi_site_instr.RfsgNrReply\x1a\x1d.multi_site_instr.RfsgNrReply\x12P\n\x13ReconfigForPlayback\x12\x1a.multi_site_instr.Playback\x1a\x1d.multi_site_instr.RfmxNrReply\x12O\n\x13StartRuTransmission\x12\x19.multi_site_instr.Nothing\x1a\x1d.multi_site_instr.RfmxNrReply\x12N\n\x12StopRuTransmission\x12\x19.multi_site_instr.Nothing\x1a\x1d.multi_site_instr.RfmxNrReplyB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OranRUServiceDef_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NOTHING._serialized_start=127
  _NOTHING._serialized_end=136
  _STATUS._serialized_start=138
  _STATUS._serialized_end=163
  _RFMXNRREPLY._serialized_start=165
  _RFMXNRREPLY._serialized_end=210
  _RFSGNRREPLY._serialized_start=212
  _RFSGNRREPLY._serialized_end=257
  _ORANRU._serialized_start=260
  _ORANRU._serialized_end=1034
# @@protoc_insertion_point(module_scope)
