# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Playback.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePlayback.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xc0\x06\n\x08Playback\x12\x36\n\x10WaveformFileName\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12;\n\x15RuTransmitFrequencyHz\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x38\n\x12RuTransmitPowerdBm\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x33\n\rRuTransmitAnt\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cTdmsFilePath\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x34\n\x0ePlaybackFolder\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x42\n\x1c\x44ownlinkCompCarrierBandWidth\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12?\n\x19\x44ownlinkSubCarrierSpacing\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x33\n\x0e\x44ownlinkCaseId\x18\t \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\tFtpServer\x18\n \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08UserName\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08Password\x18\x0c \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x0fUploadDirectory\x18\r \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x0fSourceDirectory\x18\x0e \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07\x46ileExt\x18\x0f \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Playback_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _PLAYBACK._serialized_start=69
  _PLAYBACK._serialized_end=901
# @@protoc_insertion_point(module_scope)
