# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrSemOffsets.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16RfmxNrSemOffsets.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\x95\x05\n\x0cNrSemOffsets\x12>\n\x18OffsetAbsoluteLimitStart\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12=\n\x17OffsetAbsoluteLimitStop\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12<\n\x17OffsetBandwidthIntegral\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12>\n\x18OffsetRbwFilterBandwidth\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12M\n\x13OffsetRbwFilterType\x18\x05 \x01(\x0e\x32\x30.multi_site_instr.RFmxNRMXSemOffsetRbwFilterType\x12>\n\x18OffsetRelativeLimitStart\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12=\n\x17OffsetRelativeLimitStop\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x43\n\x0eOffsetSideband\x18\x08 \x01(\x0e\x32+.multi_site_instr.RFmxNRMXSemOffsetSideband\x12:\n\x14OffsetStartFrequency\x18\t \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x39\n\x13OffsetStopFrequency\x18\n \x01(\x0b\x32\x1c.google.protobuf.DoubleValue*k\n\x1eRFmxNRMXSemOffsetRbwFilterType\x12\x14\n\x10\x46\x66tBased_010ubzm\x10\x00\x12\x14\n\x10Gaussian_010kgft\x10\x01\x12\x10\n\x0c\x46lat_010phxv\x10\x02\x12\x0b\n\x06hrkmft\x10\xf4\x03*f\n\x19RFmxNRMXSemOffsetSideband\x12\x14\n\x10Negative_010bzeh\x10\x00\x12\x14\n\x10Positive_010cudh\x10\x01\x12\x10\n\x0c\x42oth_010zxbx\x10\x02\x12\x0b\n\x06xvawnh\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrSemOffsets_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXNRMXSEMOFFSETRBWFILTERTYPE._serialized_start=740
  _RFMXNRMXSEMOFFSETRBWFILTERTYPE._serialized_end=847
  _RFMXNRMXSEMOFFSETSIDEBAND._serialized_start=849
  _RFMXNRMXSEMOFFSETSIDEBAND._serialized_end=951
  _NRSEMOFFSETS._serialized_start=77
  _NRSEMOFFSETS._serialized_end=738
# @@protoc_insertion_point(module_scope)
