# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxSpecAnIq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RfmxSpecAnIq.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xaf\x03\n\x08SpecAnIq\x12\x35\n\x0f\x41\x63quisitionTime\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x44\n\rBandwidthAuto\x18\x02 \x01(\x0e\x32-.multi_site_instr.RFmxSpecAnMXIQBandwidthAuto\x12P\n\x13\x44\x65leteRecordOnFetch\x18\x03 \x01(\x0e\x32\x33.multi_site_instr.RFmxSpecAnMXIQDeleteRecordOnFetch\x12\x36\n\x12MeasurementEnabled\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x34\n\x0fNumberOfRecords\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x34\n\x0ePretriggerTime\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x30\n\nSampleRate\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue*O\n\x1bRFmxSpecAnMXIQBandwidthAuto\x12\x11\n\rFalse_010xysi\x10\x00\x12\x10\n\x0cTrue_010afgk\x10\x01\x12\x0b\n\x06jhixgn\x10\xf4\x03*U\n!RFmxSpecAnMXIQDeleteRecordOnFetch\x12\x11\n\rFalse_010xfqj\x10\x00\x12\x10\n\x0cTrue_010qjdb\x10\x01\x12\x0b\n\x06\x64uolyj\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxSpecAnIq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXSPECANMXIQBANDWIDTHAUTO._serialized_start=506
  _RFMXSPECANMXIQBANDWIDTHAUTO._serialized_end=585
  _RFMXSPECANMXIQDELETERECORDONFETCH._serialized_start=587
  _RFMXSPECANMXIQDELETERECORDONFETCH._serialized_end=672
  _SPECANIQ._serialized_start=73
  _SPECANIQ._serialized_end=504
# @@protoc_insertion_point(module_scope)
