# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrModAccUserResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dRfmxNrModAccUserResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\"\xe1\x06\n\x13NrModAccUserResults\x12?\n\x17PdschDataPeakEvmMaximum\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x13PdschDataRmsEvmMean\x18\x02 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12?\n\x17PdschDmrsPeakEvmMaximum\x18\x03 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x13PdschDmrsRmsEvmMean\x18\x04 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12?\n\x17PdschPtrsPeakEvmMaximum\x18\x05 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x13PdschPtrsRmsEvmMean\x18\x06 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12?\n\x17PuschDataPeakEvmMaximum\x18\x07 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x13PuschDataRmsEvmMean\x18\x08 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12?\n\x17PuschDmrsPeakEvmMaximum\x18\t \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x13PuschDmrsRmsEvmMean\x18\n \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12?\n\x17PuschPtrsPeakEvmMaximum\x18\x0b \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x13PuschPtrsRmsEvmMean\x18\x0c \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12V\n\x19SchDetectedModulationType\x18\r \x01(\x0e\x32\x33.multi_site_instr.RsmxNRMXSchDetectedModulationType*\xd7\x01\n!RsmxNRMXSchDetectedModulationType\x12\x16\n\x12PiBy2_Bpsk_010ertv\x10\x00\x12\x10\n\x0cQpsk_010gawm\x10\x01\x12\x11\n\rQam16_010lqac\x10\x02\x12\x11\n\rQam64_010jwzn\x10\x03\x12\x12\n\x0eQam256_010hkfb\x10\x04\x12\x13\n\x0fQam1024_010mtja\x10\x05\x12\x10\n\x0cPsk8_010rkdc\x10\x64\x12\x1a\n\x15RequestResult_010beos\x10\x90\x03\x12\x0b\n\x06imqqpa\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrModAccUserResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RSMXNRMXSCHDETECTEDMODULATIONTYPE._serialized_start=974
  _RSMXNRMXSCHDETECTEDMODULATIONTYPE._serialized_end=1189
  _NRMODACCUSERRESULTS._serialized_start=106
  _NRMODACCUSERRESULTS._serialized_end=971
# @@protoc_insertion_point(module_scope)
