# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrChpResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrChpSubBlockResults_pb2 as RfmxNrChpSubBlockResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16RfmxNrChpResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a\x1eRfmxNrChpSubBlockResults.proto\"\x90\x01\n\x0cNrChpResults\x12<\n\x14TotalAggregatedPower\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x42\n\x12\x43hpSubBlockResults\x18\x02 \x03(\x0b\x32&.multi_site_instr.NrChpSubBlockResultsB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrChpResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRCHPRESULTS._serialized_start=131
  _NRCHPRESULTS._serialized_end=275
# @@protoc_insertion_point(module_scope)
