# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrModAccSubBlockResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrModAccCompCarrierResults_pb2 as RfmxNrModAccCompCarrierResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!RfmxNrModAccSubBlockResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a$RfmxNrModAccCompCarrierResults.proto\"\xb9\x02\n\x17NrModAccSubBlockResults\x12\x44\n\x1cSubblockInBandEmissionMargin\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x46\n\x1fSubblockLOComponentCarrierIndex\x18\x02 \x01(\x0b\x32\x1d.multi_site_instr.Int32Result\x12@\n\x19SubblockLOSubcarrierIndex\x18\x03 \x01(\x0b\x32\x1d.multi_site_instr.Int32Result\x12N\n\x18ModAccCompCarrierResults\x18\x04 \x03(\x0b\x32,.multi_site_instr.NrModAccCompCarrierResultsB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrModAccSubBlockResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRMODACCSUBBLOCKRESULTS._serialized_start=148
  _NRMODACCSUBBLOCKRESULTS._serialized_end=461
# @@protoc_insertion_point(module_scope)
