# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrTxp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRfmxNrTxp.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xa5\x03\n\x05NrTxp\x12\x34\n\x10\x41llTracesEnabled\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x33\n\x0e\x41veragingCount\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12G\n\x10\x41veragingEnabled\x18\x03 \x01(\x0e\x32-.multi_site_instr.RFmxNRMXTxpAveragingEnabled\x12\x36\n\x12MeasurementEnabled\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x39\n\x13MeasurementInterval\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x37\n\x11MeasurementOffset\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12<\n\x17NumberOfAnalysisThreads\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int32Value*O\n\x1bRFmxNRMXTxpAveragingEnabled\x12\x11\n\rFalse_010gglt\x10\x00\x12\x10\n\x0cTrue_010hoen\x10\x01\x12\x0b\n\x06okzcjo\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrTxp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXNRMXTXPAVERAGINGENABLED._serialized_start=493
  _RFMXNRMXTXPAVERAGINGENABLED._serialized_end=572
  _NRTXP._serialized_start=70
  _NRTXP._serialized_end=491
# @@protoc_insertion_point(module_scope)
