# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrAcpSubBlockOffset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dRfmxNrAcpSubBlockOffset.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xd3\x01\n\x13NrAcpSubBlockOffset\x12\x35\n\x0fOffsetFrequency\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12@\n\x1aOffsetIntegrationBandwidth\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x43\n\x0eOffsetSideband\x18\x03 \x01(\x0e\x32+.multi_site_instr.RFmxNRMXAcpOffsetSideband*f\n\x19RFmxNRMXAcpOffsetSideband\x12\x14\n\x10Negative_010kxrb\x10\x00\x12\x14\n\x10Positive_010cwzb\x10\x01\x12\x10\n\x0c\x42oth_010aqjz\x10\x02\x12\x0b\n\x06\x65\x64ochs\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrAcpSubBlockOffset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXNRMXACPOFFSETSIDEBAND._serialized_start=297
  _RFMXNRMXACPOFFSETSIDEBAND._serialized_end=399
  _NRACPSUBBLOCKOFFSET._serialized_start=84
  _NRACPSUBBLOCKOFFSET._serialized_end=295
# @@protoc_insertion_point(module_scope)
