# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrUser.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import RfmxNrPusch_pb2 as RfmxNrPusch__pb2
import RfmxNrPdsch_pb2 as RfmxNrPdsch__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10RfmxNrUser.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11RfmxNrPusch.proto\x1a\x11RfmxNrPdsch.proto\"\x8b\x02\n\x06NrUser\x12@\n\x1bNumberOfPdschConfigurations\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12@\n\x1bNumberOfPuschConfigurations\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12)\n\x04Rnti\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12(\n\x05Pusch\x18\x04 \x03(\x0b\x32\x19.multi_site_instr.NrPusch\x12(\n\x05Pdsch\x18\x05 \x03(\x0b\x32\x19.multi_site_instr.NrPdschB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrUser_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRUSER._serialized_start=109
  _NRUSER._serialized_end=376
# @@protoc_insertion_point(module_scope)
