# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxPolicy_pb2 as RfmxPolicy__pb2
import RfmxNrChpResults_pb2 as RfmxNrChpResults__pb2
import RfmxNrAcpResults_pb2 as RfmxNrAcpResults__pb2
import RfmxNrModAccResults_pb2 as RfmxNrModAccResults__pb2
import RfmxNrObwResults_pb2 as RfmxNrObwResults__pb2
import RfmxNrSemResults_pb2 as RfmxNrSemResults__pb2
import RfmxNrTxpResults_pb2 as RfmxNrTxpResults__pb2
import RfmxNrPvtResults_pb2 as RfmxNrPvtResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RfmxNrResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a\x10RfmxPolicy.proto\x1a\x16RfmxNrChpResults.proto\x1a\x16RfmxNrAcpResults.proto\x1a\x19RfmxNrModAccResults.proto\x1a\x16RfmxNrObwResults.proto\x1a\x16RfmxNrSemResults.proto\x1a\x16RfmxNrTxpResults.proto\x1a\x16RfmxNrPvtResults.proto\"\xa7\x03\n\tNrResults\x12(\n\x06Policy\x18\x01 \x01(\x0b\x32\x18.multi_site_instr.Policy\x12\x32\n\nChpResults\x18\x02 \x01(\x0b\x32\x1e.multi_site_instr.NrChpResults\x12\x32\n\nAcpResults\x18\x03 \x01(\x0b\x32\x1e.multi_site_instr.NrAcpResults\x12\x38\n\rModAccResults\x18\x04 \x01(\x0b\x32!.multi_site_instr.NrModAccResults\x12\x32\n\nObwResults\x18\x05 \x01(\x0b\x32\x1e.multi_site_instr.NrObwResults\x12\x32\n\nSemResults\x18\x06 \x01(\x0b\x32\x1e.multi_site_instr.NrSemResults\x12\x32\n\nTxpResults\x18\x07 \x01(\x0b\x32\x1e.multi_site_instr.NrTxpResults\x12\x32\n\nPvtResults\x18\x08 \x01(\x0b\x32\x1e.multi_site_instr.NrPvtResultsB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRRESULTS._serialized_start=285
  _NRRESULTS._serialized_end=708
# @@protoc_insertion_point(module_scope)
