# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxSpecAnAcpCompCarrier.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRfmxSpecAnAcpCompCarrier.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xec\x02\n\x14SpecAnAcpCompCarrier\x12\x36\n\x10\x43\x61rrierFrequency\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x41\n\x1b\x43\x61rrierIntegrationBandwidth\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x41\n\x0b\x43\x61rrierMode\x18\x03 \x01(\x0e\x32,.multi_site_instr.RFmxSpecAnMXAcpCarrierMode\x12;\n\x15\x43\x61rrierRrcFilterAlpha\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12Y\n\x17\x43\x61rrierRrcFilterEnabled\x18\x05 \x01(\x0e\x32\x38.multi_site_instr.RFmxSpecAnMXAcpCarrierRrcFilterEnabled*R\n\x1aRFmxSpecAnMXAcpCarrierMode\x12\x13\n\x0fPassive_010bksj\x10\x00\x12\x12\n\x0e\x41\x63tive_010hzuo\x10\x01\x12\x0b\n\x06kkmiwr\x10\xf4\x03*Z\n&RFmxSpecAnMXAcpCarrierRrcFilterEnabled\x12\x11\n\rFalse_010zncf\x10\x00\x12\x10\n\x0cTrue_010houo\x10\x01\x12\x0b\n\x06\x64zpdnw\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxSpecAnAcpCompCarrier_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXSPECANMXACPCARRIERMODE._serialized_start=451
  _RFMXSPECANMXACPCARRIERMODE._serialized_end=533
  _RFMXSPECANMXACPCARRIERRRCFILTERENABLED._serialized_start=535
  _RFMXSPECANMXACPCARRIERRRCFILTERENABLED._serialized_end=625
  _SPECANACPCOMPCARRIER._serialized_start=85
  _SPECANACPCOMPCARRIER._serialized_end=449
# @@protoc_insertion_point(module_scope)
