# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrPvtSubBlockResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrPvtCompCarriersResults_pb2 as RfmxNrPvtCompCarriersResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRfmxNrPvtSubBlockResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a\"RfmxNrPvtCompCarriersResults.proto\"b\n\x14NrPvtSubBlockResults\x12J\n\x16PvtCompCarriersResults\x18\x01 \x03(\x0b\x32*.multi_site_instr.NrPvtCompCarriersResultsB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrPvtSubBlockResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRPVTSUBBLOCKRESULTS._serialized_start=142
  _NRPVTSUBBLOCKRESULTS._serialized_end=240
# @@protoc_insertion_point(module_scope)
