# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrAcpSubBlock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import RfmxNrAcpSubBlockOffset_pb2 as RfmxNrAcpSubBlockOffset__pb2
import RfmxNrAcpSubBlockCompCarrier_pb2 as RfmxNrAcpSubBlockCompCarrier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RfmxNrAcpSubBlock.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dRfmxNrAcpSubBlockOffset.proto\x1a\"RfmxNrAcpSubBlockCompCarrier.proto\"\xfa\x04\n\rNrAcpSubBlock\x12\x38\n\x13NumberOfEndcOffsets\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x39\n\x14NumberOfEutraOffsets\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x36\n\x11NumberOfNROffsets\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x34\n\x0fNumberOfOffsets\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x38\n\x13NumberOfUtraOffsets\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x44\n\x1eOffsetChannelSpacingAdjustment\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x42\n\x1cSubblockIntegrationBandwidth\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x34\n\x0eSubblockOffset\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12@\n\x11\x41\x63pSubBlockOffset\x18\t \x03(\x0b\x32%.multi_site_instr.NrAcpSubBlockOffset\x12J\n\x16\x41\x63pSubBlockCompCarrier\x18\n \x03(\x0b\x32*.multi_site_instr.NrAcpSubBlockCompCarrierB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrAcpSubBlock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRACPSUBBLOCK._serialized_start=145
  _NRACPSUBBLOCK._serialized_end=779
# @@protoc_insertion_point(module_scope)
