# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxSpecAnAcpCompCarrierResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%RfmxSpecAnAcpCompCarrierResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\"\x9d\x02\n\x1bSpecAnAcpCompCarrierResults\x12<\n\x14\x43\x61rrierAbsolutePower\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x38\n\x10\x43\x61rrierFrequency\x18\x02 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x43\n\x1b\x43\x61rrierIntegrationBandwidth\x18\x03 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x41\n\x19\x43\x61rrierTotalRelativePower\x18\x04 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResultB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxSpecAnAcpCompCarrierResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _SPECANACPCOMPCARRIERRESULTS._serialized_start=114
  _SPECANACPCOMPCARRIERRESULTS._serialized_end=399
# @@protoc_insertion_point(module_scope)
