# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrSemCompCarriers.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bRfmxNrSemCompCarriers.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\x87\x01\n\x11NrSemCompCarriers\x12:\n\x14IntegrationBandwidth\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x36\n\x10RatedOutputPower\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValueB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrSemCompCarriers_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRSEMCOMPCARRIERS._serialized_start=82
  _NRSEMCOMPCARRIERS._serialized_end=217
# @@protoc_insertion_point(module_scope)
