# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrAcpSubBlockResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrAcpSubBlockOffsetResults_pb2 as RfmxNrAcpSubBlockOffsetResults__pb2
import RfmxNrAcpSubBlockCompCarriersResults_pb2 as RfmxNrAcpSubBlockCompCarriersResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRfmxNrAcpSubBlockResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a$RfmxNrAcpSubBlockOffsetResults.proto\x1a*RfmxNrAcpSubBlockCompCarriersResults.proto\"\xf9\x01\n\x14NrAcpSubBlockResults\x12\x35\n\rSubblockPower\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12N\n\x18\x41\x63pSubBlockOffsetResults\x18\x02 \x03(\x0b\x32,.multi_site_instr.NrAcpSubBlockOffsetResults\x12Z\n\x1e\x41\x63pSubBlockCompCarriersResults\x18\x03 \x03(\x0b\x32\x32.multi_site_instr.NrAcpSubBlockCompCarriersResultsB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrAcpSubBlockResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRACPSUBBLOCKRESULTS._serialized_start=189
  _NRACPSUBBLOCKRESULTS._serialized_end=438
# @@protoc_insertion_point(module_scope)
