# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrPvt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRfmxNrPvt.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xce\x05\n\x05NrPvt\x12\x34\n\x10\x41llTracesEnabled\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x33\n\x0e\x41veragingCount\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12G\n\x10\x41veragingEnabled\x18\x03 \x01(\x0e\x32-.multi_site_instr.RFmxNRMXPvtAveragingEnabled\x12\x41\n\rAveragingType\x18\x04 \x01(\x0e\x32*.multi_site_instr.RFmxNRMXPvtAveragingType\x12\x36\n\x12MeasurementEnabled\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x39\n\x13MeasurementInterval\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12U\n\x17MeasurementIntervalAuto\x18\x07 \x01(\x0e\x32\x34.multi_site_instr.RFmxNRMXPvtMeasurementIntervalAuto\x12I\n\x11MeasurementMethod\x18\x08 \x01(\x0e\x32..multi_site_instr.RFmxNRMXPvtMeasurementMethod\x12<\n\x17NumberOfAnalysisThreads\x18\t \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12<\n\x16OffPowerExclusionAfter\x18\n \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12=\n\x17OffPowerExclusionBefore\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.DoubleValue*O\n\x1bRFmxNRMXPvtAveragingEnabled\x12\x11\n\rFalse_010ntjb\x10\x00\x12\x10\n\x0cTrue_010htad\x10\x01\x12\x0b\n\x06\x62omygw\x10\xf4\x03*I\n\x18RFmxNRMXPvtAveragingType\x12\x0f\n\x0bRms_010ednx\x10\x00\x12\x0f\n\x0bLog_010teqn\x10\x01\x12\x0b\n\x06\x64lpvod\x10\xf4\x03*V\n\"RFmxNRMXPvtMeasurementIntervalAuto\x12\x11\n\rFalse_010eaxv\x10\x00\x12\x10\n\x0cTrue_010wxmq\x10\x01\x12\x0b\n\x06rzidbz\x10\xf4\x03*Y\n\x1cRFmxNRMXPvtMeasurementMethod\x12\x12\n\x0eNormal_010bkuz\x10\x00\x12\x18\n\x14\x44ynamicRange_010jmjn\x10\x01\x12\x0b\n\x06gscoka\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrPvt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXNRMXPVTAVERAGINGENABLED._serialized_start=790
  _RFMXNRMXPVTAVERAGINGENABLED._serialized_end=869
  _RFMXNRMXPVTAVERAGINGTYPE._serialized_start=871
  _RFMXNRMXPVTAVERAGINGTYPE._serialized_end=944
  _RFMXNRMXPVTMEASUREMENTINTERVALAUTO._serialized_start=946
  _RFMXNRMXPVTMEASUREMENTINTERVALAUTO._serialized_end=1032
  _RFMXNRMXPVTMEASUREMENTMETHOD._serialized_start=1034
  _RFMXNRMXPVTMEASUREMENTMETHOD._serialized_end=1123
  _NRPVT._serialized_start=70
  _NRPVT._serialized_end=788
# @@protoc_insertion_point(module_scope)
