# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxSpecAnCcdfResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bRfmxSpecAnCcdfResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\"\xf3\x01\n\x11SpecAnCcdfResults\x12\x31\n\tMeanPower\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x13MeanPowerPercentile\x18\x02 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12;\n\x14MeasuredSamplesCount\x18\x03 \x01(\x0b\x32\x1d.multi_site_instr.Int32Result\x12\x31\n\tPeakPower\x18\x04 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResultB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxSpecAnCcdfResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _SPECANCCDFRESULTS._serialized_start=104
  _SPECANCCDFRESULTS._serialized_end=347
# @@protoc_insertion_point(module_scope)
