# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrSemResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrSemSubBlockResults_pb2 as RfmxNrSemSubBlockResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16RfmxNrSemResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a\x1eRfmxNrSemSubBlockResults.proto\"\xdb\x01\n\x0cNrSemResults\x12I\n\x11MeasurementStatus\x18\x01 \x01(\x0e\x32..multi_site_instr.RsmxNRMXSemMeasurementStatus\x12<\n\x14TotalAggregatedPower\x18\x02 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x42\n\x12SemSubBlockResults\x18\x03 \x03(\x0b\x32&.multi_site_instr.NrSemSubBlockResults*k\n\x1cRsmxNRMXSemMeasurementStatus\x12\x10\n\x0c\x46\x61il_010vxkb\x10\x00\x12\x10\n\x0cPass_010whld\x10\x01\x12\x1a\n\x15RequestResult_010rgnt\x10\x90\x03\x12\x0b\n\x06ymcgjz\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrSemResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RSMXNRMXSEMMEASUREMENTSTATUS._serialized_start=352
  _RSMXNRMXSEMMEASUREMENTSTATUS._serialized_end=459
  _NRSEMRESULTS._serialized_start=131
  _NRSEMRESULTS._serialized_end=350
# @@protoc_insertion_point(module_scope)
