# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrPvtCompCarriersResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"RfmxNrPvtCompCarriersResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\"\x95\x04\n\x18NrPvtCompCarriersResults\x12=\n\x15\x41\x62soluteOffPowerAfter\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12>\n\x16\x41\x62soluteOffPowerBefore\x18\x02 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x37\n\x0f\x41\x62soluteONPower\x18\x03 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x32\n\nBurstWidth\x18\x04 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12I\n\x11MeasurementStatus\x18\x05 \x01(\x0e\x32..multi_site_instr.RsmxNRMXPvtMeasurementStatus\x12<\n\x14PeakWindowedOffPower\x18\x06 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12\x42\n\x1aPeakWindowedOffPowerMargin\x18\x07 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12@\n\x18PeakWindowedOffPowerTime\x18\x08 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult*k\n\x1cRsmxNRMXPvtMeasurementStatus\x12\x10\n\x0c\x46\x61il_010fmex\x10\x00\x12\x10\n\x0cPass_010povf\x10\x01\x12\x1a\n\x15RequestResult_010vgtz\x10\x90\x03\x12\x0b\n\x06pbabks\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrPvtCompCarriersResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RSMXNRMXPVTMEASUREMENTSTATUS._serialized_start=646
  _RSMXNRMXPVTMEASUREMENTSTATUS._serialized_end=753
  _NRPVTCOMPCARRIERSRESULTS._serialized_start=111
  _NRPVTCOMPCARRIERSRESULTS._serialized_end=644
# @@protoc_insertion_point(module_scope)
