# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrPuschCluster.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18RfmxNrPuschCluster.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\x91\x01\n\x0eNrPuschCluster\x12@\n\x1bPuschNumberOfResourceBlocks\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12=\n\x18PuschResourceBlockOffset\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrPuschCluster_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRPUSCHCLUSTER._serialized_start=79
  _NRPUSCHCLUSTER._serialized_end=224
# @@protoc_insertion_point(module_scope)
