# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrSemSubBlockResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrSemOffsetsResults_pb2 as RfmxNrSemOffsetsResults__pb2
import RfmxNrSemCompCarriersResults_pb2 as RfmxNrSemCompCarriersResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRfmxNrSemSubBlockResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a\x1dRfmxNrSemOffsetsResults.proto\x1a\"RfmxNrSemCompCarriersResults.proto\"\xdb\x01\n\x14NrSemSubBlockResults\x12\x35\n\rSubblockPower\x18\x01 \x01(\x0b\x32\x1e.multi_site_instr.DoubleResult\x12@\n\x11SemOffsetsResults\x18\x02 \x03(\x0b\x32%.multi_site_instr.NrSemOffsetsResults\x12J\n\x16SemCompCarriersResults\x18\x03 \x03(\x0b\x32*.multi_site_instr.NrSemCompCarriersResultsB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrSemSubBlockResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NRSEMSUBBLOCKRESULTS._serialized_start=174
  _NRSEMSUBBLOCKRESULTS._serialized_end=393
# @@protoc_insertion_point(module_scope)
