# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrObwResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrObwSubBlockResults_pb2 as RfmxNrObwSubBlockResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16RfmxNrObwResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a\x1eRfmxNrObwSubBlockResults.proto\"R\n\x0cNrObwResults\x12\x42\n\x12ObwSubBlockResults\x18\x01 \x03(\x0b\x32&.multi_site_instr.NrObwSubBlockResultsB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrObwResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _NROBWRESULTS._serialized_start=130
  _NROBWRESULTS._serialized_end=212
# @@protoc_insertion_point(module_scope)
