# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxPolicy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10RfmxPolicy.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xd7\x01\n\x06Policy\x12,\n\x06Signal\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nResultName\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\tTimeoutMs\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12.\n\x08RfwsFile\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\r\n\x05\x45rror\x18\x05 \x01(\tB\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxPolicy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _POLICY._serialized_start=71
  _POLICY._serialized_end=286
# @@protoc_insertion_point(module_scope)
