# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrSubBlock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import RfmxNrCompCarriers_pb2 as RfmxNrCompCarriers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14RfmxNrSubBlock.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18RfmxNrCompCarriers.proto\"\xd4\x05\n\nNrSubBlock\x12)\n\x04\x42\x61nd\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x33\n\rChannelRaster\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x46\n!ComponentCarrierAtCenterFrequency\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12Z\n\x1b\x43omponentCarrierSpacingType\x18\x04 \x01(\x0e\x32\x35.multi_site_instr.RFmxNRMXComponentCarrierSpacingType\x12@\n\x0e\x46requencyRange\x18\x05 \x01(\x0e\x32(.multi_site_instr.RFmxNRMXFrequencyRange\x12>\n\x19NumberOfComponentCarriers\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12@\n\x1aPhaseCompensationFrequency\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12J\n$SubblockEndcNominalSpacingAdjustment\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x37\n\x11SubblockFrequency\x18\t \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x41\n\x1bSubblockTransmitLOFrequency\x18\n \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x36\n\x0c\x43ompCarriers\x18\x0b \x03(\x0b\x32 .multi_site_instr.NrCompCarriers*Y\n#RFmxNRMXComponentCarrierSpacingType\x12\x13\n\x0fNominal_010jdgh\x10\x00\x12\x10\n\x0cUser_010gmed\x10\x02\x12\x0b\n\x06pponjy\x10\xf4\x03*M\n\x16RFmxNRMXFrequencyRange\x12\x12\n\x0eRange1_010zous\x10\x00\x12\x12\n\x0eRange2_010eupi\x10\x01\x12\x0b\n\x06\x61\x66\x61jat\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrSubBlock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXNRMXCOMPONENTCARRIERSPACINGTYPE._serialized_start=827
  _RFMXNRMXCOMPONENTCARRIERSPACINGTYPE._serialized_end=916
  _RFMXNRMXFREQUENCYRANGE._serialized_start=918
  _RFMXNRMXFREQUENCYRANGE._serialized_end=995
  _NRSUBBLOCK._serialized_start=101
  _NRSUBBLOCK._serialized_end=825
# @@protoc_insertion_point(module_scope)
