# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxNrModAccResults.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import ResultWrappers_pb2 as ResultWrappers__pb2
import RfmxNrModAccSubBlockResults_pb2 as RfmxNrModAccSubBlockResults__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19RfmxNrModAccResults.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14ResultWrappers.proto\x1a!RfmxNrModAccSubBlockResults.proto\"\xb7\x01\n\x0fNrModAccResults\x12Z\n\x18NoiseCompensationApplied\x18\x01 \x01(\x0e\x32\x38.multi_site_instr.RsmxNRMXModAccNoiseCompensationApplied\x12H\n\x15ModAccSubBlockResults\x18\x02 \x03(\x0b\x32).multi_site_instr.NrModAccSubBlockResults*v\n&RsmxNRMXModAccNoiseCompensationApplied\x12\x11\n\rFalse_010tiwh\x10\x00\x12\x10\n\x0cTrue_010onlk\x10\x01\x12\x1a\n\x15RequestResult_010ducw\x10\x90\x03\x12\x0b\n\x06tteofk\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxNrModAccResults_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RSMXNRMXMODACCNOISECOMPENSATIONAPPLIED._serialized_start=322
  _RSMXNRMXMODACCNOISECOMPENSATIONAPPLIED._serialized_end=440
  _NRMODACCRESULTS._serialized_start=137
  _NRMODACCRESULTS._serialized_end=320
# @@protoc_insertion_point(module_scope)
