# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfmxSpecAnCcdf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14RfmxSpecAnCcdf.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xb0\x05\n\nSpecAnCcdf\x12\x34\n\x10\x41llTracesEnabled\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x36\n\x12MeasurementEnabled\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x39\n\x13MeasurementInterval\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12<\n\x17NumberOfAnalysisThreads\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x34\n\x0fNumberOfRecords\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x38\n\x12RbwFilterBandwidth\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x37\n\x11RbwFilterRrcAlpha\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x46\n\rRbwFilterType\x18\x08 \x01(\x0e\x32/.multi_site_instr.RFmxSpecAnMXCcdfRbwFilterType\x12L\n\x10ThresholdEnabled\x18\t \x01(\x0e\x32\x32.multi_site_instr.RFmxSpecAnMXCcdfThresholdEnabled\x12\x34\n\x0eThresholdLevel\x18\n \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x46\n\rThresholdType\x18\x0b \x01(\x0e\x32/.multi_site_instr.RFmxSpecAnMXCcdfThresholdType*\x83\x01\n\x1dRFmxSpecAnMXCcdfRbwFilterType\x12\n\n\x06glaofv\x10\x00\x12\x14\n\x10Gaussian_010pfab\x10\x01\x12\x10\n\x0c\x46lat_010giyp\x10\x02\x12\x10\n\x0cNone_010mjzy\x10\x05\x12\x0f\n\x0bRrc_010knjt\x10\x06\x12\x0b\n\x06ncwwuj\x10\xf4\x03*T\n RFmxSpecAnMXCcdfThresholdEnabled\x12\x11\n\rFalse_010zqrz\x10\x00\x12\x10\n\x0cTrue_010aaiy\x10\x01\x12\x0b\n\x06muhbxz\x10\xf4\x03*X\n\x1dRFmxSpecAnMXCcdfThresholdType\x12\x14\n\x10Relative_010qlzb\x10\x00\x12\x14\n\x10\x41\x62solute_010ijkp\x10\x01\x12\x0b\n\x06lvapsn\x10\xf4\x03\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfmxSpecAnCcdf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFMXSPECANMXCCDFRBWFILTERTYPE._serialized_start=766
  _RFMXSPECANMXCCDFRBWFILTERTYPE._serialized_end=897
  _RFMXSPECANMXCCDFTHRESHOLDENABLED._serialized_start=899
  _RFMXSPECANMXCCDFTHRESHOLDENABLED._serialized_end=983
  _RFMXSPECANMXCCDFTHRESHOLDTYPE._serialized_start=985
  _RFMXSPECANMXCCDFTHRESHOLDTYPE._serialized_end=1073
  _SPECANCCDF._serialized_start=75
  _SPECANCCDF._serialized_end=763
# @@protoc_insertion_point(module_scope)
