# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RfsgNr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cRfsgNr.proto\x12\x10multi_site_instr\x1a\x1egoogle/protobuf/wrappers.proto\"\xbe\x05\n\x06RfsgNr\x12\x31\n\rOutPutEnabled\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12)\n\x05State\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12/\n\tRefSource\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\tFrequency\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12-\n\x07\x45xtLoss\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12<\n\x0eGenerationMode\x18\x06 \x01(\x0e\x32$.multi_site_instr.RfsgGenerationMode\x12\x39\n\x13WaveformRepeatCount\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x38\n\x12WaveformRepeatMode\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x33\n\rPowerLeveldBm\x18\t \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12;\n\x15UpConverterFreqOffset\x18\n \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x32\n\x0cSelectedPort\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x36\n\x10SelectedWaveform\x18\x0c \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x34\n\x0eWaveformToLoad\x18\r \x01(\x0b\x32\x1c.google.protobuf.StringValue*b\n\x12RfsgGenerationMode\x12\x18\n\x14\x46\x61lse_GenerationMode\x10\x00\x12\x13\n\x0e\x43ontinuousWave\x10\xe8\x07\x12\x10\n\x0b\x41RBWAVEFORM\x10\xe9\x07\x12\x0b\n\x06Script\x10\xea\x07\x42\x12\xaa\x02\x0fOranAptRuClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RfsgNr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017OranAptRuClient'
  _RFSGGENERATIONMODE._serialized_start=771
  _RFSGGENERATIONMODE._serialized_end=869
  _RFSGNR._serialized_start=67
  _RFSGNR._serialized_end=769
# @@protoc_insertion_point(module_scope)
